name: Sync to RITSEC GitLab
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to RITSEC GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab.ritsec.cloud/redteam/skeletor.git
          git push --mirror gitlab

